apiVersion: v1
kind: Service
metadata:
    name: "robbdikubes01-d4fc"
    labels:
        app: "robbdikubes01-d4fc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "robbdikubes01-d4fc"